//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace ITRM.Entities {
    
    
    [TableOptions(TableName="E_ITRM_RequestReasonEdit")]
    public class E_ITRM_RequestReasonEditEntity : FormEntity<E_ITRM_RequestReasonEditEntity> {
        
        private E_ITRM_RequestReasonEditVREntity _VersionEntity;
        
        private RDEntityCollection<E_ITRM_RequestReasonEditRDEntity, E_ITRM_RequestReasonEditRDMLEntity> _RD;
        
        private RDCEntityCollection<E_ITRM_RequestReasonEditRDCEntity, E_ITRM_RequestReasonEditRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_ITRM_RequestReasonEditMLEntity> _ML;
        
        private SLEntityCollection<E_ITRM_RequestReasonEditSLEntity, E_ITRM_RequestReasonEditSLMLEntity> _SL;
        
        public E_ITRM_RequestReasonEditEntity() {
            this.ML = new MLEntityCollection<E_ITRM_RequestReasonEditMLEntity>();
            this.VersionEntity = new E_ITRM_RequestReasonEditVREntity();
            this.RD = new RDEntityCollection<E_ITRM_RequestReasonEditRDEntity, E_ITRM_RequestReasonEditRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_ITRM_RequestReasonEditRDCEntity, E_ITRM_RequestReasonEditRDCMLEntity>();
            this.SL = new SLEntityCollection<E_ITRM_RequestReasonEditSLEntity, E_ITRM_RequestReasonEditSLMLEntity>();
        }
        
        public E_ITRM_RequestReasonEditVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_ITRM_RequestReasonEditRDEntity, E_ITRM_RequestReasonEditRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_ITRM_RequestReasonEditRDCEntity, E_ITRM_RequestReasonEditRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_ITRM_RequestReasonEditMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_ITRM_RequestReasonEditSLEntity, E_ITRM_RequestReasonEditSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonEditML")]
    public class E_ITRM_RequestReasonEditMLEntity : MLEntity<E_ITRM_RequestReasonEditMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _REQUESTREASON;
        
        private Bimser.Framework.Domain.DataField<string> _DESCRIPTION;
        
        [ColumnOptionsAttribute(Name="REQUESTREASON", Mandatory=false, Size=100)]
        public Bimser.Framework.Domain.DataField<string> REQUESTREASON {
            get {
                return this._REQUESTREASON;
            }
            set {
                this._REQUESTREASON = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DESCRIPTION", Mandatory=false, Size=5000)]
        public Bimser.Framework.Domain.DataField<string> DESCRIPTION {
            get {
                return this._DESCRIPTION;
            }
            set {
                this._DESCRIPTION = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonEditSL")]
    public class E_ITRM_RequestReasonEditSLEntity : SLEntity<E_ITRM_RequestReasonEditSLEntity, E_ITRM_RequestReasonEditSLMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonEditSLML")]
    public class E_ITRM_RequestReasonEditSLMLEntity : SLMLEntity<E_ITRM_RequestReasonEditSLMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonEditVR")]
    public class E_ITRM_RequestReasonEditVREntity : VersionEntity<E_ITRM_RequestReasonEditVREntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonEditRDC")]
    public class E_ITRM_RequestReasonEditRDCEntity : RDCEntity<E_ITRM_RequestReasonEditRDCEntity, E_ITRM_RequestReasonEditRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonEditRDCML")]
    public class E_ITRM_RequestReasonEditRDCMLEntity : RDCMLEntity<E_ITRM_RequestReasonEditRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonEditRD")]
    public class E_ITRM_RequestReasonEditRDEntity : RDEntity<E_ITRM_RequestReasonEditRDEntity, E_ITRM_RequestReasonEditRDMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonEditRDML")]
    public class E_ITRM_RequestReasonEditRDMLEntity : RDMLEntity<E_ITRM_RequestReasonEditRDMLEntity> {
    }
}




