//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace ITRM.Entities {
    
    
    [TableOptions(TableName="E_ITRM_RequestReasons")]
    public class E_ITRM_RequestReasonsEntity : FormEntity<E_ITRM_RequestReasonsEntity> {
        
        private E_ITRM_RequestReasonsVREntity _VersionEntity;
        
        private RDEntityCollection<E_ITRM_RequestReasonsRDEntity, E_ITRM_RequestReasonsRDMLEntity> _RD;
        
        private RDCEntityCollection<E_ITRM_RequestReasonsRDCEntity, E_ITRM_RequestReasonsRDCMLEntity> _RDC;
        
        public E_ITRM_RequestReasonsEntity() {
            this.VersionEntity = new E_ITRM_RequestReasonsVREntity();
            this.RD = new RDEntityCollection<E_ITRM_RequestReasonsRDEntity, E_ITRM_RequestReasonsRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_ITRM_RequestReasonsRDCEntity, E_ITRM_RequestReasonsRDCMLEntity>();
        }
        
        public E_ITRM_RequestReasonsVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_ITRM_RequestReasonsRDEntity, E_ITRM_RequestReasonsRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_ITRM_RequestReasonsRDCEntity, E_ITRM_RequestReasonsRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonsVR")]
    public class E_ITRM_RequestReasonsVREntity : VersionEntity<E_ITRM_RequestReasonsVREntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonsRDC")]
    public class E_ITRM_RequestReasonsRDCEntity : RDCEntity<E_ITRM_RequestReasonsRDCEntity, E_ITRM_RequestReasonsRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonsRDCML")]
    public class E_ITRM_RequestReasonsRDCMLEntity : RDCMLEntity<E_ITRM_RequestReasonsRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonsRD")]
    public class E_ITRM_RequestReasonsRDEntity : RDEntity<E_ITRM_RequestReasonsRDEntity, E_ITRM_RequestReasonsRDMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestReasonsRDML")]
    public class E_ITRM_RequestReasonsRDMLEntity : RDMLEntity<E_ITRM_RequestReasonsRDMLEntity> {
    }
}




