//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace ITRM.Entities {
    
    
    [TableOptions(TableName="E_ITRM_RequestTypeEdit")]
    public class E_ITRM_RequestTypeEditEntity : FormEntity<E_ITRM_RequestTypeEditEntity> {
        
        private E_ITRM_RequestTypeEditVREntity _VersionEntity;
        
        private RDEntityCollection<E_ITRM_RequestTypeEditRDEntity, E_ITRM_RequestTypeEditRDMLEntity> _RD;
        
        private RDCEntityCollection<E_ITRM_RequestTypeEditRDCEntity, E_ITRM_RequestTypeEditRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_ITRM_RequestTypeEditMLEntity> _ML;
        
        public E_ITRM_RequestTypeEditEntity() {
            this.ML = new MLEntityCollection<E_ITRM_RequestTypeEditMLEntity>();
            this.VersionEntity = new E_ITRM_RequestTypeEditVREntity();
            this.RD = new RDEntityCollection<E_ITRM_RequestTypeEditRDEntity, E_ITRM_RequestTypeEditRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_ITRM_RequestTypeEditRDCEntity, E_ITRM_RequestTypeEditRDCMLEntity>();
        }
        
        public E_ITRM_RequestTypeEditVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_ITRM_RequestTypeEditRDEntity, E_ITRM_RequestTypeEditRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_ITRM_RequestTypeEditRDCEntity, E_ITRM_RequestTypeEditRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_ITRM_RequestTypeEditMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypeEditML")]
    public class E_ITRM_RequestTypeEditMLEntity : MLEntity<E_ITRM_RequestTypeEditMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _REQUESTTYPE;
        
        private Bimser.Framework.Domain.DataField<string> _DESCRIPTION;
        
        [ColumnOptionsAttribute(Name="REQUESTTYPE", Mandatory=false, Size=100)]
        public Bimser.Framework.Domain.DataField<string> REQUESTTYPE {
            get {
                return this._REQUESTTYPE;
            }
            set {
                this._REQUESTTYPE = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DESCRIPTION", Mandatory=false, Size=5000)]
        public Bimser.Framework.Domain.DataField<string> DESCRIPTION {
            get {
                return this._DESCRIPTION;
            }
            set {
                this._DESCRIPTION = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypeEditVR")]
    public class E_ITRM_RequestTypeEditVREntity : VersionEntity<E_ITRM_RequestTypeEditVREntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypeEditRDC")]
    public class E_ITRM_RequestTypeEditRDCEntity : RDCEntity<E_ITRM_RequestTypeEditRDCEntity, E_ITRM_RequestTypeEditRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypeEditRDCML")]
    public class E_ITRM_RequestTypeEditRDCMLEntity : RDCMLEntity<E_ITRM_RequestTypeEditRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypeEditRD")]
    public class E_ITRM_RequestTypeEditRDEntity : RDEntity<E_ITRM_RequestTypeEditRDEntity, E_ITRM_RequestTypeEditRDMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypeEditRDML")]
    public class E_ITRM_RequestTypeEditRDMLEntity : RDMLEntity<E_ITRM_RequestTypeEditRDMLEntity> {
    }
}




