//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace ITRM.Entities {
    
    
    [TableOptions(TableName="E_ITRM_ReviewerSelect")]
    public class E_ITRM_ReviewerSelectEntity : FormEntity<E_ITRM_ReviewerSelectEntity> {
        
        private E_ITRM_ReviewerSelectVREntity _VersionEntity;
        
        private RDEntityCollection<E_ITRM_ReviewerSelectRDEntity, E_ITRM_ReviewerSelectRDMLEntity> _RD;
        
        private RDCEntityCollection<E_ITRM_ReviewerSelectRDCEntity, E_ITRM_ReviewerSelectRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_ITRM_ReviewerSelectMLEntity> _ML;
        
        private SLEntityCollection<E_ITRM_ReviewerSelectSLEntity, E_ITRM_ReviewerSelectSLMLEntity> _SL;
        
        public E_ITRM_ReviewerSelectEntity() {
            this.ML = new MLEntityCollection<E_ITRM_ReviewerSelectMLEntity>();
            this.VersionEntity = new E_ITRM_ReviewerSelectVREntity();
            this.RD = new RDEntityCollection<E_ITRM_ReviewerSelectRDEntity, E_ITRM_ReviewerSelectRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_ITRM_ReviewerSelectRDCEntity, E_ITRM_ReviewerSelectRDCMLEntity>();
            this.SL = new SLEntityCollection<E_ITRM_ReviewerSelectSLEntity, E_ITRM_ReviewerSelectSLMLEntity>();
        }
        
        public E_ITRM_ReviewerSelectVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_ITRM_ReviewerSelectRDEntity, E_ITRM_ReviewerSelectRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_ITRM_ReviewerSelectRDCEntity, E_ITRM_ReviewerSelectRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_ITRM_ReviewerSelectMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_ITRM_ReviewerSelectSLEntity, E_ITRM_ReviewerSelectSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_ReviewerSelectML")]
    public class E_ITRM_ReviewerSelectMLEntity : MLEntity<E_ITRM_ReviewerSelectMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _REVIEWREASON;
        
        [ColumnOptionsAttribute(Name="REVIEWREASON", Mandatory=false, Size=5000)]
        public Bimser.Framework.Domain.DataField<string> REVIEWREASON {
            get {
                return this._REVIEWREASON;
            }
            set {
                this._REVIEWREASON = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_ReviewerSelectSL")]
    public class E_ITRM_ReviewerSelectSLEntity : SLEntity<E_ITRM_ReviewerSelectSLEntity, E_ITRM_ReviewerSelectSLMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_ReviewerSelectSLML")]
    public class E_ITRM_ReviewerSelectSLMLEntity : SLMLEntity<E_ITRM_ReviewerSelectSLMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_ReviewerSelectVR")]
    public class E_ITRM_ReviewerSelectVREntity : VersionEntity<E_ITRM_ReviewerSelectVREntity> {
    }
    
    [TableOptions(TableName="E_ITRM_ReviewerSelectRDC")]
    public class E_ITRM_ReviewerSelectRDCEntity : RDCEntity<E_ITRM_ReviewerSelectRDCEntity, E_ITRM_ReviewerSelectRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_ReviewerSelectRDCML")]
    public class E_ITRM_ReviewerSelectRDCMLEntity : RDCMLEntity<E_ITRM_ReviewerSelectRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_ReviewerSelectRD")]
    public class E_ITRM_ReviewerSelectRDEntity : RDEntity<E_ITRM_ReviewerSelectRDEntity, E_ITRM_ReviewerSelectRDMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_ReviewerSelectRDML")]
    public class E_ITRM_ReviewerSelectRDMLEntity : RDMLEntity<E_ITRM_ReviewerSelectRDMLEntity> {
    }
}




