//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace ITRM.Entities {
    
    
    [TableOptions(TableName="E_ITRM_PriorityEdit")]
    public class E_ITRM_PriorityEditEntity : FormEntity<E_ITRM_PriorityEditEntity> {
        
        private E_ITRM_PriorityEditVREntity _VersionEntity;
        
        private RDEntityCollection<E_ITRM_PriorityEditRDEntity, E_ITRM_PriorityEditRDMLEntity> _RD;
        
        private RDCEntityCollection<E_ITRM_PriorityEditRDCEntity, E_ITRM_PriorityEditRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_ITRM_PriorityEditMLEntity> _ML;
        
        public E_ITRM_PriorityEditEntity() {
            this.ML = new MLEntityCollection<E_ITRM_PriorityEditMLEntity>();
            this.VersionEntity = new E_ITRM_PriorityEditVREntity();
            this.RD = new RDEntityCollection<E_ITRM_PriorityEditRDEntity, E_ITRM_PriorityEditRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_ITRM_PriorityEditRDCEntity, E_ITRM_PriorityEditRDCMLEntity>();
        }
        
        public E_ITRM_PriorityEditVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_ITRM_PriorityEditRDEntity, E_ITRM_PriorityEditRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_ITRM_PriorityEditRDCEntity, E_ITRM_PriorityEditRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_ITRM_PriorityEditMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_PriorityEditML")]
    public class E_ITRM_PriorityEditMLEntity : MLEntity<E_ITRM_PriorityEditMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _PRIORITY;
        
        private Bimser.Framework.Domain.DataField<string> _DESCRIPTION;
        
        [ColumnOptionsAttribute(Name="PRIORITY", Mandatory=false, Size=100)]
        public Bimser.Framework.Domain.DataField<string> PRIORITY {
            get {
                return this._PRIORITY;
            }
            set {
                this._PRIORITY = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DESCRIPTION", Mandatory=false, Size=5000)]
        public Bimser.Framework.Domain.DataField<string> DESCRIPTION {
            get {
                return this._DESCRIPTION;
            }
            set {
                this._DESCRIPTION = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_PriorityEditVR")]
    public class E_ITRM_PriorityEditVREntity : VersionEntity<E_ITRM_PriorityEditVREntity> {
    }
    
    [TableOptions(TableName="E_ITRM_PriorityEditRDC")]
    public class E_ITRM_PriorityEditRDCEntity : RDCEntity<E_ITRM_PriorityEditRDCEntity, E_ITRM_PriorityEditRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_PriorityEditRDCML")]
    public class E_ITRM_PriorityEditRDCMLEntity : RDCMLEntity<E_ITRM_PriorityEditRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_PriorityEditRD")]
    public class E_ITRM_PriorityEditRDEntity : RDEntity<E_ITRM_PriorityEditRDEntity, E_ITRM_PriorityEditRDMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_PriorityEditRDML")]
    public class E_ITRM_PriorityEditRDMLEntity : RDMLEntity<E_ITRM_PriorityEditRDMLEntity> {
    }
}




