//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace ITRM.Entities {
    
    
    [TableOptions(TableName="E_ITRM_RequestTypes")]
    public class E_ITRM_RequestTypesEntity : FormEntity<E_ITRM_RequestTypesEntity> {
        
        private E_ITRM_RequestTypesVREntity _VersionEntity;
        
        private RDEntityCollection<E_ITRM_RequestTypesRDEntity, E_ITRM_RequestTypesRDMLEntity> _RD;
        
        private RDCEntityCollection<E_ITRM_RequestTypesRDCEntity, E_ITRM_RequestTypesRDCMLEntity> _RDC;
        
        public E_ITRM_RequestTypesEntity() {
            this.VersionEntity = new E_ITRM_RequestTypesVREntity();
            this.RD = new RDEntityCollection<E_ITRM_RequestTypesRDEntity, E_ITRM_RequestTypesRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_ITRM_RequestTypesRDCEntity, E_ITRM_RequestTypesRDCMLEntity>();
        }
        
        public E_ITRM_RequestTypesVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_ITRM_RequestTypesRDEntity, E_ITRM_RequestTypesRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_ITRM_RequestTypesRDCEntity, E_ITRM_RequestTypesRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypesVR")]
    public class E_ITRM_RequestTypesVREntity : VersionEntity<E_ITRM_RequestTypesVREntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypesRDC")]
    public class E_ITRM_RequestTypesRDCEntity : RDCEntity<E_ITRM_RequestTypesRDCEntity, E_ITRM_RequestTypesRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypesRDCML")]
    public class E_ITRM_RequestTypesRDCMLEntity : RDCMLEntity<E_ITRM_RequestTypesRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypesRD")]
    public class E_ITRM_RequestTypesRDEntity : RDEntity<E_ITRM_RequestTypesRDEntity, E_ITRM_RequestTypesRDMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestTypesRDML")]
    public class E_ITRM_RequestTypesRDMLEntity : RDMLEntity<E_ITRM_RequestTypesRDMLEntity> {
    }
}




