//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace ITRM.Entities {
    
    
    [TableOptions(TableName="E_ITRM_RequestEdit")]
    public class E_ITRM_RequestEditEntity : FormEntity<E_ITRM_RequestEditEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _REQUESTOR;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _REQUESTDATE;
        
        private E_ITRM_RequestEditVREntity _VersionEntity;
        
        private RDEntityCollection<E_ITRM_RequestEditRDEntity, E_ITRM_RequestEditRDMLEntity> _RD;
        
        private RDCEntityCollection<E_ITRM_RequestEditRDCEntity, E_ITRM_RequestEditRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_ITRM_RequestEditMLEntity> _ML;
        
        private SLEntityCollection<E_ITRM_RequestEditSLEntity, E_ITRM_RequestEditSLMLEntity> _SL;
        
        public E_ITRM_RequestEditEntity() {
            this.ML = new MLEntityCollection<E_ITRM_RequestEditMLEntity>();
            this.VersionEntity = new E_ITRM_RequestEditVREntity();
            this.RD = new RDEntityCollection<E_ITRM_RequestEditRDEntity, E_ITRM_RequestEditRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_ITRM_RequestEditRDCEntity, E_ITRM_RequestEditRDCMLEntity>();
            this.SL = new SLEntityCollection<E_ITRM_RequestEditSLEntity, E_ITRM_RequestEditSLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="REQUESTOR", Mandatory=false, Size=100)]
        public Bimser.Framework.Domain.DataField<string> REQUESTOR {
            get {
                return this._REQUESTOR;
            }
            set {
                this._REQUESTOR = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="REQUESTDATE", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> REQUESTDATE {
            get {
                return this._REQUESTDATE;
            }
            set {
                this._REQUESTDATE = value;
            }
        }
        
        public E_ITRM_RequestEditVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_ITRM_RequestEditRDEntity, E_ITRM_RequestEditRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_ITRM_RequestEditRDCEntity, E_ITRM_RequestEditRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_ITRM_RequestEditMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_ITRM_RequestEditSLEntity, E_ITRM_RequestEditSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_RequestEditML")]
    public class E_ITRM_RequestEditMLEntity : MLEntity<E_ITRM_RequestEditMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _IMAGES;
        
        private Bimser.Framework.Domain.DataField<string> _DESCRIPTION;
        
        private Bimser.Framework.Domain.DataField<string> _DEVELOPERDESCRIPTION;
        
        private Bimser.Framework.Domain.DataField<string> _REVIEWREASON;
        
        [ColumnOptionsAttribute(Name="IMAGES", Mandatory=false, Size=2147483647)]
        public Bimser.Framework.Domain.DataField<string> IMAGES {
            get {
                return this._IMAGES;
            }
            set {
                this._IMAGES = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DESCRIPTION", Mandatory=false, Size=5000)]
        public Bimser.Framework.Domain.DataField<string> DESCRIPTION {
            get {
                return this._DESCRIPTION;
            }
            set {
                this._DESCRIPTION = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DEVELOPERDESCRIPTION", Mandatory=false, Size=5000)]
        public Bimser.Framework.Domain.DataField<string> DEVELOPERDESCRIPTION {
            get {
                return this._DEVELOPERDESCRIPTION;
            }
            set {
                this._DEVELOPERDESCRIPTION = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="REVIEWREASON", Mandatory=false, Size=5000)]
        public Bimser.Framework.Domain.DataField<string> REVIEWREASON {
            get {
                return this._REVIEWREASON;
            }
            set {
                this._REVIEWREASON = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_RequestEditSL")]
    public class E_ITRM_RequestEditSLEntity : SLEntity<E_ITRM_RequestEditSLEntity, E_ITRM_RequestEditSLMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestEditSLML")]
    public class E_ITRM_RequestEditSLMLEntity : SLMLEntity<E_ITRM_RequestEditSLMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestEditVR")]
    public class E_ITRM_RequestEditVREntity : VersionEntity<E_ITRM_RequestEditVREntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestEditRDC")]
    public class E_ITRM_RequestEditRDCEntity : RDCEntity<E_ITRM_RequestEditRDCEntity, E_ITRM_RequestEditRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestEditRDCML")]
    public class E_ITRM_RequestEditRDCMLEntity : RDCMLEntity<E_ITRM_RequestEditRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestEditRD")]
    public class E_ITRM_RequestEditRDEntity : RDEntity<E_ITRM_RequestEditRDEntity, E_ITRM_RequestEditRDMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_RequestEditRDML")]
    public class E_ITRM_RequestEditRDMLEntity : RDMLEntity<E_ITRM_RequestEditRDMLEntity> {
    }
}




