//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace ITRM.Entities {
    
    
    [TableOptions(TableName="E_ITRM_Priorities")]
    public class E_ITRM_PrioritiesEntity : FormEntity<E_ITRM_PrioritiesEntity> {
        
        private E_ITRM_PrioritiesVREntity _VersionEntity;
        
        private RDEntityCollection<E_ITRM_PrioritiesRDEntity, E_ITRM_PrioritiesRDMLEntity> _RD;
        
        private RDCEntityCollection<E_ITRM_PrioritiesRDCEntity, E_ITRM_PrioritiesRDCMLEntity> _RDC;
        
        public E_ITRM_PrioritiesEntity() {
            this.VersionEntity = new E_ITRM_PrioritiesVREntity();
            this.RD = new RDEntityCollection<E_ITRM_PrioritiesRDEntity, E_ITRM_PrioritiesRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_ITRM_PrioritiesRDCEntity, E_ITRM_PrioritiesRDCMLEntity>();
        }
        
        public E_ITRM_PrioritiesVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_ITRM_PrioritiesRDEntity, E_ITRM_PrioritiesRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_ITRM_PrioritiesRDCEntity, E_ITRM_PrioritiesRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
    }
    
    [TableOptions(TableName="E_ITRM_PrioritiesVR")]
    public class E_ITRM_PrioritiesVREntity : VersionEntity<E_ITRM_PrioritiesVREntity> {
    }
    
    [TableOptions(TableName="E_ITRM_PrioritiesRDC")]
    public class E_ITRM_PrioritiesRDCEntity : RDCEntity<E_ITRM_PrioritiesRDCEntity, E_ITRM_PrioritiesRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_PrioritiesRDCML")]
    public class E_ITRM_PrioritiesRDCMLEntity : RDCMLEntity<E_ITRM_PrioritiesRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_PrioritiesRD")]
    public class E_ITRM_PrioritiesRDEntity : RDEntity<E_ITRM_PrioritiesRDEntity, E_ITRM_PrioritiesRDMLEntity> {
    }
    
    [TableOptions(TableName="E_ITRM_PrioritiesRDML")]
    public class E_ITRM_PrioritiesRDMLEntity : RDMLEntity<E_ITRM_PrioritiesRDMLEntity> {
    }
}




